server:
  port: 8080
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081/realms/secure-order}
  cloud:
    gateway:
      routes:
        - id: users
          uri: ${USER_SERVICE_URI:http://user-service:8082}
          predicates: [ Path=/api/users/** ]
        - id: products
          uri: ${PRODUCT_SERVICE_URI:http://product-service:8083}
          predicates: [ Path=/api/products/** ]
        - id: orders
          uri: ${ORDER_SERVICE_URI:http://order-service:8084}
          predicates: [ Path=/api/orders/** ]
        - id: auth
          uri: ${AUTH_SERVICE_URI:http://auth-service:8088}
          predicates: [ Path=/api/auth/** ]
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
